name: e_scooter
description: "E-Scooter"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  #map
  google_maps_flutter: ^2.12.1
  flutter_polyline_points: ^2.1.0
  http: ^1.3.0
  #icons- fonts
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/map_style_dark.json


